#!/usr/bin/env bash

# Do not edit - autogenerated by pluc. More info at https://github.com/dawsbot/pluc

alias gid="git diff"
alias gaa="git add -A"
alias co="git checkout"
alias gp="git push"
alias lyn="learnyounode"
alias tir="thinking-in-react"
